config/routes.rb
Medicamentos::Application.routes.draw do
  resources :medicines

  resources :durations

  resources :frequencies

  resources :amounts

  resources :patients

  

end

app/models/frequency.rb
class Frequency < ActiveRecord::Base
	validates :frecuencia, :horas_frecuencia, presence: true
end

app/controllers/frequencies_controller.rb
class FrequenciesController < ApplicationController
  before_action :set_frequency, only: [:show, :edit, :update, :destroy]

  # GET /frequencies
  # GET /frequencies.json
  def index
    @frequencies = Frequency.all
    @frequency = Frequency.new
  end

  # GET /frequencies/1
  # GET /frequencies/1.json
  def show
  end

  # GET /frequencies/new
  def new
    @frequency = Frequency.new
  end

  # GET /frequencies/1/edit
  def edit
  end

  # POST /frequencies
  # POST /frequencies.json
  def create
    @frequency = Frequency.new(frequency_params)

    respond_to do |format|
      if @frequency.save
        format.html { redirect_to frequencies_path, notice: 'Frequency was successfully created.' }
        format.json { render action: 'show', status: :created, location: @frequency }
      else
        format.html { render action: 'new' }
        format.json { render json: @frequency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /frequencies/1
  # PATCH/PUT /frequencies/1.json
  def update
    respond_to do |format|
      if @frequency.update(frequency_params)
        format.html { redirect_to @frequency, notice: 'Frequency was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @frequency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /frequencies/1
  # DELETE /frequencies/1.json
  def destroy
    @frequency.destroy
    respond_to do |format|
      format.html { redirect_to frequencies_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_frequency
      @frequency = Frequency.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def frequency_params
      params.require(:frequency).permit(:frecuencia, :horas_frecuencia)
    end
end

app/helpers/frequencies_helper.rb
module FrequenciesHelper
end

app/views/frequencies/_form.html.erb
<%= form_for(@frequency) do |f| %>
  <% if @frequency.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@frequency.errors.count, "error") %> prohibited this frequency from being saved:</h2>

      <ul>
      <% @frequency.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :frecuencia %><br>
    <%= f.text_field :frecuencia %>
  </div>
  <div class="field">
    <%= f.label :horas_frecuencia %><br>
    <%= f.number_field :horas_frecuencia %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/frequencies/edit.html.erb
<h1>Editing frequency</h1>

<%= render 'form' %>

<%= link_to 'Show', @frequency %> |
<%= link_to 'Back', frequencies_path %>

app/views/frequencies/index.html.erb
<h1>Frecuencias</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Frecuencia</th>
      <th>Horas frecuencia</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @frequencies.each do |frequency| %>
      <tr>
        <td><%= frequency.frecuencia %></td>
        <td><%= frequency.horas_frecuencia %></td>
        <td><%= link_to 'Show', frequency %></td>
        <td><%= link_to 'Edit', edit_frequency_path(frequency) %></td>
        <td><%= link_to 'Destroy', frequency, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<h2>Agregar Frecuencia</h2>
<%= render "form" %>

app/views/frequencies/new.html.erb
<h1>New frequency</h1>

<%= render 'form' %>

<%= link_to 'Back', frequencies_path %>

app/views/frequencies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Frecuencia:</strong>
  <%= @frequency.frecuencia %>
</p>

<p>
  <strong>Horas frecuencia:</strong>
  <%= @frequency.horas_frecuencia %>
</p>

<%= link_to 'Edit', edit_frequency_path(@frequency) %> |
<%= link_to 'Back', frequencies_path %>