config/routes.rb
Medicamentos::Application.routes.draw do
  resources :medicines

  resources :durations

  resources :frequencies

  resources :amounts

  resources :patients

  

end

app/models/duration.rb
class Duration < ActiveRecord::Base
end

app/controllers/durations_controller.rb
class DurationsController < ApplicationController
  before_action :set_duration, only: [:show, :edit, :update, :destroy]

  # GET /durations
  # GET /durations.json
  def index
    @durations = Duration.all
    @duration = Duration.new
  end

  # GET /durations/1
  # GET /durations/1.json
  def show
  end

  # GET /durations/new
  def new
    @duration = Duration.new
  end

  # GET /durations/1/edit
  def edit
  end

  # POST /durations
  # POST /durations.json
  def create
    @duration = Duration.new(duration_params)

    respond_to do |format|
      if @duration.save
        format.html { redirect_to durations_path, notice: 'Duration was successfully created.' }
        format.json { render action: 'show', status: :created, location: @duration }
      else
        format.html { render action: 'new' }
        format.json { render json: @duration.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /durations/1
  # PATCH/PUT /durations/1.json
  def update
    respond_to do |format|
      if @duration.update(duration_params)
        format.html { redirect_to @duration, notice: 'Duration was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @duration.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /durations/1
  # DELETE /durations/1.json
  def destroy
    @duration.destroy
    respond_to do |format|
      format.html { redirect_to durations_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_duration
      @duration = Duration.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def duration_params
      params.require(:duration).permit(:duracion, :dias_duracion)
    end
end

app/helpers/durations_helper.rb
module DurationsHelper
end

app/views/durations/_form.html.erb
<%= form_for(@duration) do |f| %>
  <% if @duration.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@duration.errors.count, "error") %> prohibited this duration from being saved:</h2>

      <ul>
      <% @duration.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :duracion %><br>
    <%= f.text_field :duracion %>
  </div>
  <div class="field">
    <%= f.label :dias_duracion %><br>
    <%= f.number_field :dias_duracion %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/durations/edit.html.erb
<h1>Editing duration</h1>

<%= render 'form' %>

<%= link_to 'Show', @duration %> |
<%= link_to 'Back', durations_path %>

app/views/durations/index.html.erb
<h1>Duraciones</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Duracion</th>
      <th>Dias duracion</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @durations.each do |duration| %>
      <tr>
        <td><%= duration.duracion %></td>
        <td><%= duration.dias_duracion %></td>
        <td><%= link_to 'Show', duration %></td>
        <td><%= link_to 'Edit', edit_duration_path(duration) %></td>
        <td><%= link_to 'Destroy', duration, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<h2>Agregar duracion</h2>
<%= render "form" %>

app/views/durations/new.html.erb
<h1>New duration</h1>

<%= render 'form' %>

<%= link_to 'Back', durations_path %>

app/views/durations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Duracion:</strong>
  <%= @duration.duracion %>
</p>

<p>
  <strong>Dias duracion:</strong>
  <%= @duration.dias_duracion %>
</p>

<%= link_to 'Edit', edit_duration_path(@duration) %> |
<%= link_to 'Back', durations_path %>