config/routes.rb
Medicamentos::Application.routes.draw do
  resources :medicines

  resources :durations

  resources :frequencies

  resources :amounts

  resources :patients

  

end

app/models/patient.rb
class Patient < ActiveRecord::Base

	validates :nombre_uno, :apellido_uno, :documento_identidad, :fecha_nacimiento, :telefono, presence: true
	validates :documento_identidad, uniqueness: true
	validates :documento_identidad, :telefono, :celular, numericality: true

	def nombre_completo
		self.nombre_uno + " " + self.nombre_dos + " " + self.apellido_uno + " " + self.apellido_dos
	end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.all
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
        format.json { render action: 'show', status: :created, location: @patient }
      else
        format.html { render action: 'new' }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:nombre_uno, :nombre_dos, :apellido_uno, :apellido_dos, :documento_identidad, :fecha_nacimiento, :edad, :telefono, :celular, :email, :direccion)
    end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.erb
<%= form_for([@patient], {:class=>"form-horizontal"}) do |f| %>
  <% if @patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% @patient.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre_uno %><br>
    <%= f.text_field :nombre_uno %>
  </div>
  <div class="field">
    <%= f.label :nombre_dos %><br>
    <%= f.text_field :nombre_dos %>
  </div>
  <div class="field">
    <%= f.label :apellido_uno %><br>
    <%= f.text_field :apellido_uno %>
  </div>
  <div class="field">
    <%= f.label :apellido_dos %><br>
    <%= f.text_field :apellido_dos %>
  </div>
  <div class="field">
    <%= f.label :documento_identidad %><br>
    <%= f.number_field :documento_identidad %>
  </div>
  <div class="field">
    <%= f.label :fecha_nacimiento %><br>
    <%= f.date_select :fecha_nacimiento %>
  </div>
  <div class="field">
    <%= f.label :edad %><br>
    <%= f.number_field :edad %>
  </div>
  <div class="field">
    <%= f.label :telefono %><br>
    <%= f.text_field :telefono %>
  </div>
  <div class="field">
    <%= f.label :celular %><br>
    <%= f.text_field :celular %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :direccion %><br>
    <%= f.text_field :direccion %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/patients/edit.html.erb
<h1>Editing patient</h1>

<%= render 'form' %>

<%= link_to 'Show', @patient %> |
<%= link_to 'Back', patients_path %>

app/views/patients/index.html.erb
<h3>Pacientes</h3>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Documento identidad</th>
      <th>Fecha nacimiento</th>
      <th>Edad</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.nombre_completo %></td>
        <td><%= patient.documento_identidad %></td>
        <td><%= patient.fecha_nacimiento %></td>
        <td><%= patient.edad %></td>
        <td><%= link_to 'Show', patient %></td>
        <td><%= link_to 'Edit', edit_patient_path(patient) %></td>
        <td><%= link_to 'Destroy', patient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<h3>Agregar Paciente</h3>
<%= link_to 'New Patient', new_patient_path %>

app/views/patients/new.html.erb
<h1>New patient</h1>

<%= render 'form' %>

<%= link_to 'Back', patients_path %>

app/views/patients/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @patient.nombre_completo %></h1>
<p>
  <strong>Documento identidad:</strong>
  <%= @patient.documento_identidad %>
</p>

<p>
  <strong>Fecha nacimiento:</strong>
  <%= @patient.fecha_nacimiento %>
</p>

<p>
  <strong>Edad:</strong>
  <%= @patient.edad %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @patient.telefono %>
</p>

<p>
  <strong>Celular:</strong>
  <%= @patient.celular %>
</p>

<p>
  <strong>Email:</strong>
  <%= @patient.email %>
</p>

<p>
  <strong>Direccion:</strong>
  <%= @patient.direccion %>
</p>

<%= link_to 'Edit', edit_patient_path(@patient) %> |
<%= link_to 'Back', patients_path %>